
DROP TABLE IF EXISTS Books;

Create Table IF NOT EXISTS Books (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT UNIQUE,
	Uid VARCHAR(50) NOT NULL,
	Title VARCHAR(30) NOT NULL,
	Author VARCHAR(30) NOT NULL,
    Category VARCHAR(20) NOT NULL,
	Subcategory VARCHAR(20) NOT NULL,
	Pages INT,
    OwnerUid VARCHAR(50) NOT NULL,
	ImgSrc VARCHAR(50),
	Available TINYINT NOT NULL,
	Buy TINYINT NOT NULL,
	Rent TINYINT NOT NULL,
	BuyAmount INT,
	RentAmount INT,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Uid),
	FOREIGN KEY (OwnerUid) REFERENCES Users(uid),
	CONSTRAINT UNIQUE_BOOK UNIQUE (Title , Author , OwnerUid)
) ENGINE=INNODB;



CREATE INDEX SEARCH_BY_CATEGORY ON Books (Category,Subcategory);

