DROP TABLE IF EXISTS Complaints;

Create Table Complaints (
	id BIGINT(19) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grievantId BIGINT(19) UNSIGNED NOT NULL,
	complaint VARCHAR(1000) NOT NULL,
	status TINYINT NOT NULL,
	creationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (grievantId) REFERENCES USERS(id)
) ENGINE=INNODB;


CREATE INDEX SEARCH_BY_STATUS ON Complaints (status);