\DROP TABLE IF EXISTS `NOTIFICATIONS`;

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
	Id INT AUTO_INCREMENT,
	Uid VARCHAR(50) NOT NULL,
	ReceiverUid VARCHAR(50) NOT NULL,
	Type TINYINT NOT NULL,
	BookRequestUid VARCHAR(50),
	NewBookUid VARCHAR(50),
	Status TINYINT NOT NULL,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Uid),
	FOREIGN KEY (ReceiverUid) REFERENCES Users(uid)
) ENGINE=INNODB;

