DROP TABLE IF EXISTS `OneTimePasswords`;

CREATE TABLE OneTimePasswords (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Uid VARCHAR(32) UNIQUE,
	UserUid VARCHAR(32),
	Otp VARCHAR(4),
	Accepted TINYINT(1) DEFAULT 0,
	Attempts TINYINT DEFAULT 0,
	GeneratedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ExpiryTime DATETIME NOT NULL,
	IsExpired TINYINT DEFAULT 0,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;