DROP TABLE IF EXISTS Orders;

CREATE TABLE Orders (
	id BIGINT(19) UNSIGNED AUTO_INCREMENT,
	referenceNo VARCHAR(30) NOT NULL UNIQUE,
	requestRefNo VARCHAR(30) NOT NULL UNIQUE,
	type TINYINT NOT NULL,
	status TINYINT NOT NULL,
	buyerId BIGINT(19) UNSIGNED NOT NULL,
	sellerId BIGINT(19) UNSIGNED NOT NULL,
	amount DOUBLE NOT NULL,
	creationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (requestRefNo) REFERENCES BookRequests(referenceNo)
) ENGINE=INNODB;


CREATE INDEX SEARCH_BY_BUYERID ON Orders (buyerId);

CREATE INDEX SEARCH_BY_SELLERID ON Orders (sellerId);