DROP TABLE IF EXISTS `PasswordResetLink`;

CREATE TABLE PasswordResetLink (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Uid VARCHAR(32) UNIQUE,
	UserUid VARCHAR(32),
	LongUrl VARCHAR(150),
	ShortUrl VARCHAR(20),
	GeneratedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ExpiryTime DATETIME NOT NULL,
	IsExpired TINYINT,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;