DROP TABLE IF EXISTS `Quotes`;


CREATE TABLE IF NOT EXISTS `Quotes` (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT UNIQUE,
	Uid VARCHAR(50) NOT NULL,
	BookUid VARCHAR(50) NOT NULL,
	UserUid VARCHAR(50) NOT NULL,
	Status TINYINT NOT NULL,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Uid)
) ENGINE=INNODB;

