DROP TABLE IF EXISTS Subscriptions;

CREATE TABLE Subscriptions (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Uid VARCHAR(50) PRIMARY KEY,
	UserUid VARCHAR(50) NOT NULL,
	Type TINYINT NOT NULL,
	StartTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EndTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Active TINYINT NOT NULL DEFAULT 1,
	CreationTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationtime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (UserUid) REFERENCES Users (Uid)
) ENGINE=INNODB;


