DROP TABLE IF EXISTS Orders;

CREATE TABLE Orders (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT UNIQUE,
	Uid VARCHAR(50) NOT NULL UNIQUE,
	RequestUid VARCHAR(50) NOT NULL UNIQUE,
	Type TINYINT NOT NULL,
	Status TINYINT NOT NULL,
	BuyerUid VARCHAR(50) NOT NULL,
	SellerUid VARCHAR(50) NOT NULL,
	Amount DOUBLE NOT NULL,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Uid)
) ENGINE=INNODB;

