DROP TABLE IF EXISTS Complaints;

Create Table Complaints (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	GrievantId BIGINT(19) UNSIGNED NOT NULL,
	Complaint VARCHAR(1000) NOT NULL,
	Status TINYINT NOT NULL,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;


CREATE INDEX SEARCH_BY_STATUS ON Complaints (Status);