DROP TABLE IF EXISTS Feedbacks;

CREATE TABLE Feedbacks (
	Id BIGINT(19) AUTO_INCREMENT UNIQUE,
	Uid VARCHAR(50) PRIMARY KEY,
	UserUid VARCHAR(50) NOT NULL,
	Feedback VARCHAR(500) NOT NULL,
	Status TINYINT DEFAULT NULL,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;


DELIMITER $$
Create Trigger Feedback_Update
	BEFORE UPDATE ON Feedbacks
	FOR EACH ROW
	BEGIN
		SET NEW.LastModificationTime=CURRENT_TIMESTAMP;
	END;
$$
DELIMITER ;
