DROP DATABASE IF EXISTS Sharebooks_Analytics;
DROP DATABASE IF EXISTS Sharebooks_AWS;
DROP DATABASE IF EXISTS Sharebooks_Config;
DROP DATABASE IF EXISTS Sharebooks_Core;
DROP DATABASE IF EXISTS Sharebooks_Master;
DROP DATABASE IF EXISTS Sharebooks_SMS;
DROP DATABASE IF EXISTS Sharebooks_SystemTracking;
DROP DATABASE IF EXISTS Sharebooks_UserAccounts;
DROP DATABASE IF EXISTS Sharebooks_UserExperience;


CREATE DATABASE IF NOT EXISTS Sharebooks_Analytics;
CREATE DATABASE IF NOT EXISTS Sharebooks_AWS;
CREATE DATABASE IF NOT EXISTS Sharebooks_Config;
CREATE DATABASE IF NOT EXISTS Sharebooks_Core; 
CREATE DATABASE IF NOT EXISTS Sharebooks_Master; 
CREATE DATABASE IF NOT EXISTS Sharebooks_SMS; 
CREATE DATABASE IF NOT EXISTS Sharebooks_SystemTracking;
CREATE DATABASE IF NOT EXISTS Sharebooks_UserAccounts; 
CREATE DATABASE IF NOT EXISTS Sharebooks_UserExperience;

