DROP TABLE IF EXISTS Cities;

CREATE TABLE IF NOT EXISTS Cities (
	Id int(5) AUTO_INCREMENT PRIMARY KEY,
	City VARCHAR(40) NOT NULL,
	StateId int NOT NULL,
	PRIMARY KEY (Id),
	CONSTRAINT UNIQUE_CITY UNIQUE (City , StateId)
) ENGINE=InnoDB;