DROP TABLE IF EXISTS States;


CREATE TABLE States (
	Id int AUTO_INCREMENT,
	Name VARCHAR(20) NOT NULL UNIQUE,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
