DROP PROCEDURE IF EXISTS `books_basic`;
DROP PROCEDURE IF EXISTS `users`;
DROP PROCEDURE IF EXISTS `users_active`;

DELIMITER $$

CREATE PROCEDURE books_basic()
BEGIN 
	SELECT ID,TITLE,AUTHORNAME,CATEGORY,SUBCATEGORY FROM BOOKS;
END
$$


CREATE PROCEDURE users()
BEGIN
	SELECT ID,USERNAME,NAME,DOB,MOBILENO,ACTIVE FROM USERS;
END
$$

CREATE PROCEDURE users_active()
BEGIN
	SELECT ID,USERNAME,NAME,DOB,MOBILENO,ACTIVE FROM USERS WHERE ACTIVE=1;
END
$$


DELIMITER ;