DROP TABLE IF EXISTS Cities;

CREATE TABLE Cities (
	id int AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	stateId int NOT NULL,
	creationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	CONSTRAINT UNIQUE_CITY UNIQUE (name , stateId),
	FOREIGN KEY (stateId) REFERENCES States(id)
) ENGINE=INNODB;