/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lakshya.singhal' at '22/3/19 12:28 PM' with Gradle 2.5
 *
 * @author lakshya.singhal, @date 22/3/19 12:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
