DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
	Id BIGINT(19) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Uid VARCHAR(50) NOT NULL UNIQUE,
	Username VARCHAR(50) NOT NULL UNIQUE,
	Password VARCHAR(150) NOT NULL,
	Name VARCHAR(40) NOT NULL,
	DOB DATE NOT NULL,
	Age TINYINT NOT NULL,
	Address TINYTEXT NOT NULL,
	City VARCHAR(20) NOT NULL,
	State VARCHAR(20) NOT NULL,
	Pincode VARCHAR(6) NOT NULL,
	ContactNo VARCHAR(10) NOT NULL UNIQUE,
	Preferences TEXT,
	AccountType TINYINT NOT NULL,
	IsRegistered TINYINT,
	SubscriptionStatus TINYINT NOT NULL DEFAULT 0,
	Active TINYINT NOT NULL DEFAULT 1,
	CreationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModificationTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;




DELIMITER $$
CREATE TRIGGER before_user_insert
	BEFORE INSERT ON Users
	FOR EACH ROW
	BEGIN 
		IF (NEW.username REGEXP '^[A-Z0-9]+[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,20}$') = 0 THEN
			SIGNAL SQLSTATE '45000'
				SET MESSAGE_TEXT = 'Username is not in correct format.';
		END IF;
	END;
$$
DELIMITER ;



